runtime: python39
entrypoint: gunicorn -b :$PORT create_app:app

handlers:
- url: /static
  static_dir: static

  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
